# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fd5ad774be24e3493192520ca1ac6749883ba3e44e8c841caeda3ffd11435c401e4b4c8f0f24229e7baddbfb8b2bf9a25f5ca3f0d72e441d6a8a77e8f6cfca8

test:
  secret_key_base: b072c2701c4f3fc1594e525dab6470a24ad60045254f63a1e392fcd1cfc094539eed0fa26b629310ba151d8d227585fd9ff77dd7ac7c2b1aa35c3eeeaa44527f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
